### PR TITLE
Few improvements on user callback generation

### LINKED ISSUE #704: Fix invalid user callbacks generation
```
<slomo> you pass a Box<Option<P>> as user_data, so a *mut Option<P>. but you then cast it inside the trampoline to a &Box<Option<P>>
<slomo> that's one level of indirection too much inside the trampoline
<slomo> it should be a &Option<P>
<slomo> oh looked at the wrong function. nevermind, but that is a problem elsewhere ;)
<slomo> this one is a different case of the same general problem
<slomo> you pass an &Option<P> as user_data but get out of the user_data a *mut P
<slomo> the Option<_> got lost along the way
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #704.

This currently fixes two things:

* Remove the invalid indirection (`Box::<Option<X>>.as_ptr()` -> `&Box<Option<X>>` is not longer a thing)
* Added the missing `Option` <s>(yep, everything is an `Option` by default)</s> (it's now correctly handled everywhere)
* No more `GString` parameters: they're replaced with `&str` now
* Fix invalid Send/Sync bounds (by default, I was giving both of them :p)
* Fix invalid nullable "status" from destroy callbacks.

I intend to fix the other issues on this PR as well so please don't merge! :)

### CODE REVIEW

File: src/codegen/function_body_chunk.rs [hunk 1]
```diff
@@ -356,7 +356,7 @@ impl Builder {
                         if is_destroy || trampoline.scope.is_async() {
                             format!("Box_::from_raw({} as *mut _)", func)
                         } else if trampoline.scope.is_call() {
-                            format!("{} as *const _ as usize as *mut {}",
+                            format!("{} as *const _ as usize as *mut Option<{}>",
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/codegen/function_body_chunk.rs]: Simpler that way. Everything is an `Option`. :)

[the remark this answers is not in the document]
Comment (sdroege) [reply src/codegen/function_body_chunk.rs]: On one side, yes. On the other side you need to unwrap the `Option<_>`, which adds code (quite a bit due to potentially panicking) and also involves runtime costs :)

[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply src/codegen/function_body_chunk.rs]: And of course you're right. I'll need to add another field to know if the callback is nullable. I'll do it next.

**Comment by GuillaumeGomez** [comment]
I think this is ready! If you want to look at the result, take a look at https://github.com/gtk-rs/gtk/pull/760

**Comment by sdroege** [comment]
> I think this is ready! If you want to look at the result, take a look at [gtk-rs/gtk#760](https://github.com/gtk-rs/gtk/pull/760)

Great :) I'll review tomorrow or maybe later

**Comment by GuillaumeGomez** [comment]
I fixed the nullable bug spotted on gtk PR (which has been updated too).

File: src/analysis/functions.rs [hunk 2]
```diff
@@ -389,7 +397,7 @@ fn analyze_function(
             Some(obj) => {
                 match env.library.type_(type_tid) {
                     library::Type::Class(_) => obj.concurrency,
-                    _ => library::Concurrency::SendSync,
+                    _ => library::Concurrency::None,
```
Comment (EPashkin) [inline src/analysis/functions.rs]: Maybe interface and record need be here too,
please add comment for checking later (at first glance I don't find any)

Comment (GuillaumeGomez) [reply src/analysis/functions.rs]: Good point! I add the comment.

Comment (sdroege) [reply src/analysis/functions.rs]: Both are needed here, yes.

Comment (sdroege) [reply src/analysis/functions.rs]: I mean, add them and not just a FIXME comment :P

**Comment by sdroege** [comment]
:+1:

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by sdroege** [comment]
All good for me

**Comment by EPashkin** [comment]
Then lets merge, @GuillaumeGomez Thanks

**Comment by GuillaumeGomez** [comment]
I'll send the regens this evening.
