### PR TITLE
Correctly generate glib::Error import

### LINKED ISSUE #862: `glib::Error` gets `use`d as `use Error` instead of `use glib::Error` when in the `manual` array
Generated code looks like https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/blob/master/gstreamer-editing-services/src/auto/asset.rs#L24 ; with `GLib.Error` in the `manual` array of the `Gir.toml`.

This can be worked around with `use glib::Error;` at the root of the crate (as is currently done by most if not all gtk-rs crates), but without this it'd fail to compile.

I think the `use` statement should be `use glib::Error` directly, to avoid this issue :)

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #862.

cc @EPashkin @sdroege @Ekleog

### CODE REVIEW

File: src/analysis/imports.rs [hunk 1]
```diff
@@ -175,7 +175,10 @@ impl Imports {
     ///
     /// Returns `None` if name matches crate name exactly. Otherwise returns
     /// name with crate name prefix stripped or full name if there was no match.
-    fn strip_crate_name<'a>(&self, name: &'a str) -> Option<&'a str> {
+    fn strip_crate_name<'a>(&self, mut name: &'a str) -> Option<&'a str> {
+        if name == "Error" && self.crate_name != "glib" {
+            name = "glib::Error";
```
Comment (sdroege) [inline src/analysis/imports.rs]: This does not seem correct. Why does it even end up here without the `glib::` prefix?

Comment (GuillaumeGomez) [reply src/analysis/imports.rs]: This is actually an excellent question. Since it's part of `manual` imports everytime, it \*should\* not be needed. This fix is therefore incomplete. I need to find what's going on.

**Comment by GuillaumeGomez** [comment]
I now extended the fix. Way cleaner, better, faster, etc. :)

**Comment by GuillaumeGomez** [comment]
And now with fixed formatting.

**Comment by GuillaumeGomez** [comment]
ping @EPashkin @sdroege :)

**Comment by EPashkin** [comment]
@GuillaumeGomez Thanks, I will wait for @sdroege just in case

**Comment by sdroege** [comment]
:+1:
