### PR TITLE
Fix clippy warnings

### LINKED ISSUE #971: Lots of clippy warnings with latest clippy
See title, needs to be cleaned up :)

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #971.

cc @sdroege @EPashkin

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Is it a big issue if it doesn't compile on stable? :-°

File: src/codegen/function_body_chunk.rs [hunk 1]
```diff
@@ -1080,17 +1076,15 @@ impl Builder {
                 ref mem_mode,
             } = *par
             {
-                if self
-                    .transformations
-                    .iter()
-                    .any(|tr| match tr.transformation_type {
+                if self.transformations.iter().any(|tr| {
```
Comment (sdroege) [inline src/codegen/function_body_chunk.rs:1079]: Clippy complains about this still, if you don't want to change it can you add an `#[allow(clippy::...)]` in the right place?

**Comment by sdroege** [comment]
Looks good to me otherwise, no function changes and can go in after that last warning is fixed or ignored

File: src/codegen/function_body_chunk.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/codegen/function_body_chunk.rs:1079]: It doesn't on nightly, so...

**Comment by GuillaumeGomez** [comment]
Let's get it in then!
